"""initial_schema

Revision ID: c447645246ac
Revises: 
Create Date: 2026-07-18 00:24:56.073113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import finops_sentinel.adapters.persistence.sqlalchemy_repo


# revision identifiers, used by Alembic.
revision: str = 'c447645246ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_finding_id'), 'audit_events', ['finding_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_finding_id'), 'decisions', ['finding_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resource_ref', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.Column('tags_at_detection', sa.String(), nullable=False),
    sa.Column('est_monthly_cost_usd', finops_sentinel.adapters.persistence.sqlalchemy_repo.SafeNumeric(), nullable=False),
    sa.Column('llm_summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'notified', 'approved', 'denied', 'remediated', 'failed', 'expired')", name='check_finding_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_resource_ref'), 'findings', ['resource_ref'], unique=False)
    op.create_index(op.f('ix_findings_rule'), 'findings', ['rule'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_arn', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('current_tags', sa.String(), nullable=False),
    sa.Column('lifecycle', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('active', 'deleted')", name='check_resource_lifecycle'),
    sa.CheckConstraint("resource_type IN ('ebs_volume', 'elastic_ip', 'ec2_instance', 'ebs_snapshot')", name='check_resource_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_resource_id'), 'resources', ['resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_resource_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule'), table_name='findings')
    op.drop_index(op.f('ix_findings_resource_ref'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_decisions_finding_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_audit_events_finding_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
